/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package program_si_rawat_inap;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gilang
 */
public class data_pasien extends javax.swing.JFrame {

    /**
     * Creates new form data_pasien
     */
    public data_pasien() {
        initComponents();
        setLocationRelativeTo(null);
        kd.setEnabled(false);
        ubah.setEnabled(false);
        buang.setEnabled(false);
        autonumber();
        tampil();
        bersih();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        close = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        kd = new javax.swing.JTextField();
        nm = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tmpt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tgl = new javax.swing.JComboBox();
        bln = new javax.swing.JComboBox();
        thn = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        jk = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        alamat = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        gd = new javax.swing.JComboBox();
        tambah = new javax.swing.JButton();
        ubah = new javax.swing.JButton();
        buang = new javax.swing.JButton();
        refresh = new javax.swing.JButton();
        format = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(235, 239, 246));

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(44, 65, 127));
        jLabel4.setText("Data Pasien");

        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_delete_25px.png"))); // NOI18N
        close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(close)
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(close))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel4)))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        tabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No", "Kode Pasien", "Nama Pasien", "Tempat Lahir", "Tanggal Lahir", "Jenis Kelamin", "Alamat", "Golongan Darah"
            }
        ));
        tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabel);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(44, 65, 127));
        jLabel7.setText("Kode Pasien");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(44, 65, 127));
        jLabel8.setText("Nama Pasien");

        kd.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        kd.setForeground(new java.awt.Color(44, 65, 127));

        nm.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        nm.setForeground(new java.awt.Color(44, 65, 127));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(44, 65, 127));
        jLabel9.setText("Tempat Lahir");

        tmpt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tmpt.setForeground(new java.awt.Color(44, 65, 127));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(44, 65, 127));
        jLabel10.setText("Tanggal Lahir");

        tgl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tgl.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        bln.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bln.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember" }));

        thn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        thn.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2020", "2019", "2018", "2017", "2016", "2015", "2014", "2013", "2012", "2011", "2010", "2009", "2008", "2007", "2006", "2005", "2004", "2003", "2002", "2001", "2000", "1999", "1998", "1997", "1996", "1995", "1994", "1993", "1992", "1991", "1990", "1989", "1988", "1987", "1986", "1985", "1984", "1983", "1982", "1981", "1980", "1979", "1978", "1977", "1976", "1975", "1974", "1973", "1972", "1971", "1970", "1969", "1968", "1967", "1966", "1965", "1964", "1963", "1962", "1961", "1960", "1959", "1958", "1957", "1956", "1955", "1954", "1953", "1952", "1951", "1950", "1949", "1948", "1947", "1946", "1945", "1944", "1943", "1942", "1941", "1940", "1939", "1938", "1937", "1936", "1935", "1934", "1933", "1932", "1931", "1930", "1929", "1928", "1927", "1926", "1925", "1924", "1923", "1922", "1921", "1920", "1919", "1918", "1917", "1916", "1915", "1914", "1913", "1912", "1911", "1910", "1909", "1908", "1907", "1906", "1905", "1904", "1903", "1902", "1901" }));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(44, 65, 127));
        jLabel11.setText("Jenis Kelamin");

        jk.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jk.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pria", "Wanita" }));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(44, 65, 127));
        jLabel12.setText("Alamat");

        alamat.setColumns(20);
        alamat.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        alamat.setForeground(new java.awt.Color(44, 65, 127));
        alamat.setRows(5);
        jScrollPane3.setViewportView(alamat);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(44, 65, 127));
        jLabel13.setText("Golongan Darah");

        gd.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        gd.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A", "B", "AB", "O", "--" }));

        tambah.setBackground(new java.awt.Color(255, 255, 255));
        tambah.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        tambah.setForeground(new java.awt.Color(44, 65, 127));
        tambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_plus_math_30px_1.png"))); // NOI18N
        tambah.setText("Tambah");
        tambah.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });

        ubah.setBackground(new java.awt.Color(255, 255, 255));
        ubah.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        ubah.setForeground(new java.awt.Color(44, 65, 127));
        ubah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_edit_30px.png"))); // NOI18N
        ubah.setText("Ubah");
        ubah.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubahActionPerformed(evt);
            }
        });

        buang.setBackground(new java.awt.Color(255, 255, 255));
        buang.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        buang.setForeground(new java.awt.Color(44, 65, 127));
        buang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_trash_30px.png"))); // NOI18N
        buang.setText("Buang");
        buang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buangActionPerformed(evt);
            }
        });

        refresh.setBackground(new java.awt.Color(255, 255, 255));
        refresh.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        refresh.setForeground(new java.awt.Color(44, 65, 127));
        refresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_refresh_30px.png"))); // NOI18N
        refresh.setText("Refresh");
        refresh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });

        format.setBackground(new java.awt.Color(255, 255, 255));
        format.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        format.setForeground(new java.awt.Color(44, 65, 127));
        format.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_delete_database_30px.png"))); // NOI18N
        format.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        format.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel7)
                            .addComponent(jLabel13))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(gd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(tgl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(bln, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(thn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(nm)
                                .addComponent(tmpt)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(kd, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(refresh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(format))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(tambah)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(ubah, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(buang, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 846, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(kd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(nm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tmpt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(tgl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bln, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(thn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(jk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(gd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tambah)
                            .addComponent(ubah)
                            .addComponent(buang))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(refresh)
                            .addComponent(format)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2)))
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new home().setVisible(true);
    }//GEN-LAST:event_closeMouseClicked

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
        // TODO add your handling code here:
        tambah();
    }//GEN-LAST:event_tambahActionPerformed

    private void ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubahActionPerformed
        // TODO add your handling code here:
        edit();
    }//GEN-LAST:event_ubahActionPerformed

    private void buangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buangActionPerformed
        // TODO add your handling code here:
        delete();
    }//GEN-LAST:event_buangActionPerformed

    private void tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMouseClicked
        // TODO add your handling code here:
        pilihtabel();
    }//GEN-LAST:event_tabelMouseClicked

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
        // TODO add your handling code here:
        bersih();
        tampil();
        autonumber();
    }//GEN-LAST:event_refreshActionPerformed

    private void formatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formatActionPerformed
        // TODO add your handling code here:
        format();
    }//GEN-LAST:event_formatActionPerformed

//=====================================================================================================================================================
    
    public DefaultTableModel tabmod;
    
    public void tampil(){
        Object[] baris = {"No", "Kode Pasien", "Nama Pasien", "Tempat Lahir", "Tanggal Lahir", "Jenis Kelamin", "Alamat", "Golongan Darah"};
        tabmod = new DefaultTableModel(null, baris);
        tabel.setModel(tabmod);
        Connection con = null;
        Statement st = null;
        
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/rawat_inap","root","");
            st = con.createStatement();
            String sql = "Select * from db_pasien";
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()){
                String id = rs.getString("id");
                String kd_pasien = rs.getString("kd_pasien");
                String nm_pasien = rs.getString("nm_pasien");
                String tmpt_lhr = rs.getString("tmpt_lhr");
                String tgl_lhr = rs.getString("tgl_lhr");
                String jk = rs.getString("jk");
                String alamat = rs.getString("alamat");
                String gol_darah = rs.getString("gol_darah");
                String[] data = {id, kd_pasien, nm_pasien, tmpt_lhr, tgl_lhr, jk, alamat, gol_darah};
                tabmod.addRow(data);
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Koneksi gagal\n"+e.getMessage(),null,JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public void tambah(){
        String a,b,c,d,ee,f,g,h,i,smpn;
        a = kd.getText();
        b = nm.getText();
        c = tmpt.getText();
        d = (String)tgl.getSelectedItem();
        ee = (String)bln.getSelectedItem();
        f = (String)thn.getSelectedItem();
        g = (String)jk.getSelectedItem();
        h = alamat.getText();
        i = (String)gd.getSelectedItem();
               
        Connection con = null;
        Statement st = null;
        
        try {
                Class.forName("com.mysql.jdbc.Driver");
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/rawat_inap","root","");
                st = con.createStatement();
                //simpan = "INSERT INTO akun(nm, usrnm, pass) VALUES ('"+nma+"','"+usrnme+"','"+pw+"')";
                smpn = "INSERT INTO db_pasien(kd_pasien, nm_pasien, tmpt_lhr, tgl_lhr, jk, alamat, gol_darah) VALUES ('"+a+"','"+b+"','"+c+"','"+d+"/"+ee+"/"+f+"','"+g+"','"+h+"','"+i+"')";
                st.executeUpdate(smpn);
                tampil();
                JOptionPane.showMessageDialog(null, "Berhasil ditambah");
                nm.requestFocus();
                autonumber();
                bersih();
            } 
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage(),null,JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public void edit(){
        String a,b,c,d,ee,f,g,h,i,smpn;
        a = kd.getText();
        b = nm.getText();
        c = tmpt.getText();
        d = (String)tgl.getSelectedItem();
        ee = (String)bln.getSelectedItem();
        f = (String)thn.getSelectedItem();
        g = (String)jk.getSelectedItem();
        h = alamat.getText();
        i = (String)gd.getSelectedItem();
               
        Connection con = null;
        Statement st = null;
        
        try {
                Class.forName("com.mysql.jdbc.Driver");
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/rawat_inap","root","");
                st = con.createStatement();
                //simpan = "INSERT INTO akun(nm, usrnm, pass) VALUES ('"+nma+"','"+usrnme+"','"+pw+"')";
                smpn = "UPDATE db_pasien SET nm_pasien='"+b+"', tmpt_lhr='"+c+"', tgl_lhr='"+d+"/"+ee+"/"+f+"', jk='"+g+"', alamat='"+h+"', gol_darah='"+i+"'WHERE kd_pasien='"+a+"'";
                st.executeUpdate(smpn);
                tampil();
                JOptionPane.showMessageDialog(null, "Berhasil diubah");
                nm.requestFocus();
                autonumber();
                bersih();
            } 
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage(),null,JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public void delete(){
        Connection con = null;
        Statement st = null;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/rawat_inap","root","");
            st = con.createStatement();
            String sql = "delete from db_pasien where kd_pasien=?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, kd.getText());
            pst.execute();
            autonumber();
            tampil();
            bersih();
            JOptionPane.showMessageDialog(null, "Berhasil dihapus");
                
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage(),null,JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public void pilihtabel(){
        ubah.setEnabled(true);
        buang.setEnabled(true);
        tambah.setEnabled(false);
        int baris = tabel.getSelectedRow();
        String kdd = tabel.getValueAt(baris, 1).toString();
        String np = tabel.getValueAt(baris, 2).toString();
        String tl = tabel.getValueAt(baris, 3).toString();
        String tg = tabel.getValueAt(baris, 4).toString();
        String jkk = tabel.getValueAt(baris, 5).toString();
        String al = tabel.getValueAt(baris, 6).toString();
        String gol = tabel.getValueAt(baris, 7).toString();
        kd.setText(kdd);
        nm.setText(np);
        tmpt.setText(tl);
 
        String[] h = tg.split("/");
        tgl.setSelectedItem(h[0]);
        bln.setSelectedItem(h[1]);
        thn.setSelectedItem(h[2]);
        
        jk.setSelectedItem(jkk);
        alamat.setText(al);
        gd.setSelectedItem(gol);
    }
    
    public void bersih(){
        nm.requestFocus();
        ubah.setEnabled(false);
        buang.setEnabled(false);
        tambah.setEnabled(true);
        nm.setText("");
        tgl.setSelectedIndex(0);
        bln.setSelectedIndex(0);
        thn.setSelectedIndex(0);
        jk.setSelectedIndex(0);
        gd.setSelectedIndex(0);
        tmpt.setText("");
        alamat.setText("");
    }
    
    public void autonumber(){
        String nokd = "KP000";
        int i = 0;
        Connection con = null;
        Statement st = null;
        try{
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/rawat_inap","root","");
            st = con.createStatement();
            String sql = "Select kd_pasien from db_pasien";
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()){
                nokd = rs.getString("kd_pasien");
            }
            nokd = nokd.substring(2);
            i = Integer.parseInt(nokd)+1;
            
            nokd = "00"+i;
            nokd = "KP"+nokd.substring(nokd.length()-3);
            kd.setText(nokd);

        }
        catch (Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage(),null,JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public void format(){
        Connection con = null;
        Statement st = null;
        if (JOptionPane.showConfirmDialog(null,"Kosongkan tabel ?", null,JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
            try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/rawat_inap","root","");
            st = con.createStatement();
            String sql = "truncate table db_pasien";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.execute();
            tampil();
            bersih();
            autonumber();
            JOptionPane.showMessageDialog(null, "Tabel berhasil di kosongkan");
                
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null, e.getMessage(),null,JOptionPane.ERROR_MESSAGE);
            }
        }
        else{
            
        }
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(data_pasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(data_pasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(data_pasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(data_pasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new data_pasien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea alamat;
    private javax.swing.JComboBox bln;
    private javax.swing.JButton buang;
    private javax.swing.JLabel close;
    private javax.swing.JButton format;
    private javax.swing.JComboBox gd;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox jk;
    private javax.swing.JTextField kd;
    private javax.swing.JTextField nm;
    private javax.swing.JButton refresh;
    private javax.swing.JTable tabel;
    private javax.swing.JButton tambah;
    private javax.swing.JComboBox tgl;
    private javax.swing.JComboBox thn;
    private javax.swing.JTextField tmpt;
    private javax.swing.JButton ubah;
    // End of variables declaration//GEN-END:variables
}
