/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package program_si_rawat_inap;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gilang
 */
public class data_dokter extends javax.swing.JFrame {

    /**
     * Creates new form data_dokter
     */
    public data_dokter() {
        initComponents();
        setLocationRelativeTo(null);
        kd.setEnabled(false);
        ubah.setEnabled(false);
        buang.setEnabled(false);
        autonumber();
        bersih();
        tampil();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        spesial = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        alamat = new javax.swing.JTextArea();
        format = new javax.swing.JButton();
        tambah = new javax.swing.JButton();
        buang = new javax.swing.JButton();
        refresh = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        nm = new javax.swing.JTextField();
        ubah = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        kd = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        close = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(235, 239, 246));

        spesial.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        spesial.setForeground(new java.awt.Color(44, 65, 127));

        alamat.setColumns(20);
        alamat.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        alamat.setForeground(new java.awt.Color(44, 65, 127));
        alamat.setRows(5);
        jScrollPane3.setViewportView(alamat);

        format.setBackground(new java.awt.Color(255, 255, 255));
        format.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        format.setForeground(new java.awt.Color(44, 65, 127));
        format.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_delete_database_30px.png"))); // NOI18N
        format.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        format.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formatActionPerformed(evt);
            }
        });

        tambah.setBackground(new java.awt.Color(255, 255, 255));
        tambah.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        tambah.setForeground(new java.awt.Color(44, 65, 127));
        tambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_plus_math_30px_1.png"))); // NOI18N
        tambah.setText("Tambah");
        tambah.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });

        buang.setBackground(new java.awt.Color(255, 255, 255));
        buang.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        buang.setForeground(new java.awt.Color(44, 65, 127));
        buang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_trash_30px.png"))); // NOI18N
        buang.setText("Buang");
        buang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buangActionPerformed(evt);
            }
        });

        refresh.setBackground(new java.awt.Color(255, 255, 255));
        refresh.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        refresh.setForeground(new java.awt.Color(44, 65, 127));
        refresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_refresh_30px.png"))); // NOI18N
        refresh.setText("Refresh");
        refresh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(44, 65, 127));
        jLabel7.setText("Kode Dokter");

        nm.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        nm.setForeground(new java.awt.Color(44, 65, 127));

        ubah.setBackground(new java.awt.Color(255, 255, 255));
        ubah.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        ubah.setForeground(new java.awt.Color(44, 65, 127));
        ubah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_edit_30px.png"))); // NOI18N
        ubah.setText("Ubah");
        ubah.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubahActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(44, 65, 127));
        jLabel9.setText("Spesialis");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(44, 65, 127));
        jLabel8.setText("Nama Dokter");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(44, 65, 127));
        jLabel12.setText("Alamat");

        kd.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        kd.setForeground(new java.awt.Color(44, 65, 127));

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(44, 65, 127));
        jLabel4.setText("Data Dokter");

        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_delete_25px.png"))); // NOI18N
        close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 795, Short.MAX_VALUE)
                .addComponent(close)
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(close))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel4)))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        tabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "No", "Kode Dokter", "Nama Dokter", "Spesialis", "Alamat"
            }
        ));
        tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabel);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(tambah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ubah, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buang, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(format))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(nm)
                                .addComponent(spesial, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(kd, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 643, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spesial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tambah)
                            .addComponent(ubah)
                            .addComponent(buang))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(refresh)
                            .addComponent(format))))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new home().setVisible(true);
    }//GEN-LAST:event_closeMouseClicked

    private void formatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formatActionPerformed
        // TODO add your handling code here:
        format();
    }//GEN-LAST:event_formatActionPerformed

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
        // TODO add your handling code here:
        bersih();
        tampil();
        autonumber();
    }//GEN-LAST:event_refreshActionPerformed

    private void buangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buangActionPerformed
        // TODO add your handling code here:
        delete();
    }//GEN-LAST:event_buangActionPerformed

    private void ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubahActionPerformed
        // TODO add your handling code here:
        edit();
    }//GEN-LAST:event_ubahActionPerformed

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
        // TODO add your handling code here:
        tambah();
    }//GEN-LAST:event_tambahActionPerformed

    private void tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMouseClicked
        // TODO add your handling code here:
        pilihtabel();
    }//GEN-LAST:event_tabelMouseClicked

//=====================================================================================================================================================    
    
    public DefaultTableModel tabmod;
    
    public void tampil(){
        Object[] baris = {"No", "Kode Dokter", "Nama Dokter", "Spesialis", "Alamat"};
        tabmod = new DefaultTableModel(null, baris);
        tabel.setModel(tabmod);
        Connection con = null;
        Statement st = null;
        
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/rawat_inap","root","");
            st = con.createStatement();
            String sql = "Select * from db_dokter";
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()){
                String id = rs.getString("id");
                String kd_dokter = rs.getString("kd_dokter");
                String nm_dokter = rs.getString("nm_dokter");
                String spesialis = rs.getString("spesialis");
                String alamat = rs.getString("alamat");
                String[] data = {id, kd_dokter, nm_dokter, spesialis, alamat};
                tabmod.addRow(data);
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Koneksi gagal\n"+e.getMessage(),null,JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public void tambah(){
        String a,b,c,d,smpn;
        a = kd.getText();
        b = nm.getText();
        c = spesial.getText();
        d = alamat.getText();
               
        Connection con = null;
        Statement st = null;
        
        try {
                Class.forName("com.mysql.jdbc.Driver");
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/rawat_inap","root","");
                st = con.createStatement();
                //simpan = "INSERT INTO akun(nm, usrnm, pass) VALUES ('"+nma+"','"+usrnme+"','"+pw+"')";
                smpn = "INSERT INTO db_dokter(kd_dokter, nm_dokter, spesialis, alamat) VALUES ('"+a+"','Dr."+b+"','"+c+"','"+d+"')";
                st.executeUpdate(smpn);
                tampil();
                JOptionPane.showMessageDialog(null, "Berhasil ditambah");
                nm.requestFocus();
                autonumber();
                bersih();
            } 
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage(),null,JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public void edit(){
        String a,b,c,d,smpn;
        a = kd.getText();
        b = nm.getText();
        c = spesial.getText();
        d = alamat.getText();
               
        Connection con = null;
        Statement st = null;
        
        try {
                Class.forName("com.mysql.jdbc.Driver");
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/rawat_inap","root","");
                st = con.createStatement();
                smpn = "UPDATE db_dokter SET nm_dokter='"+b+"', spesialis='"+c+"', alamat='"+d+"'WHERE kd_dokter='"+a+"'";
                st.executeUpdate(smpn);
                tampil();
                JOptionPane.showMessageDialog(null, "Berhasil diubah");
                nm.requestFocus();
                autonumber();
                bersih();
            } 
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage(),null,JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public void delete(){
        Connection con = null;
        Statement st = null;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/rawat_inap","root","");
            st = con.createStatement();
            String sql = "delete from db_dokter where kd_dokter=?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, kd.getText());
            pst.execute();
            autonumber();
            tampil();
            bersih();
            JOptionPane.showMessageDialog(null, "Berhasil dihapus");
                
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage(),null,JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public void pilihtabel(){
        ubah.setEnabled(true);
        buang.setEnabled(true);
        tambah.setEnabled(false);
        int baris = tabel.getSelectedRow();
        String kdd = tabel.getValueAt(baris, 1).toString();
        String nd = tabel.getValueAt(baris, 2).toString();
        String spes = tabel.getValueAt(baris, 3).toString();
        String alam = tabel.getValueAt(baris, 4).toString();
        kd.setText(kdd);
        nm.setText(nd);
        spesial.setText(spes);
        alamat.setText(alam);
    }
    
    public void bersih(){
        nm.requestFocus();
        ubah.setEnabled(false);
        buang.setEnabled(false);
        tambah.setEnabled(true);
        nm.setText("");
        spesial.setText("");
        alamat.setText("");
    }
    
    public void autonumber(){
        String nokd = "KD000";
        int i = 0;
        Connection con = null;
        Statement st = null;
        try{
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/rawat_inap","root","");
            st = con.createStatement();
            String sql = "Select kd_dokter from db_dokter";
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()){
                nokd = rs.getString("kd_dokter");
            }
            nokd = nokd.substring(2);
            i = Integer.parseInt(nokd)+1;
            
            nokd = "00"+i;
            nokd = "KD"+nokd.substring(nokd.length()-3);
            kd.setText(nokd);

        }
        catch (Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage(),null,JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public void format(){
        Connection con = null;
        Statement st = null;
        if (JOptionPane.showConfirmDialog(null,"Kosongkan tabel ?", null,JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
            try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/rawat_inap","root","");
            st = con.createStatement();
            String sql = "truncate table db_dokter";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.execute();
            tampil();
            bersih();
            autonumber();
            JOptionPane.showMessageDialog(null, "Tabel berhasil di kosongkan");
                
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null, e.getMessage(),null,JOptionPane.ERROR_MESSAGE);
            }
        }
        else{
            
        }
    }
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(data_dokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(data_dokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(data_dokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(data_dokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new data_dokter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea alamat;
    private javax.swing.JButton buang;
    private javax.swing.JLabel close;
    private javax.swing.JButton format;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField kd;
    private javax.swing.JTextField nm;
    private javax.swing.JButton refresh;
    private javax.swing.JTextField spesial;
    private javax.swing.JTable tabel;
    private javax.swing.JButton tambah;
    private javax.swing.JButton ubah;
    // End of variables declaration//GEN-END:variables
}
